[package]
name = "atmpt"
authors = ["Marcelo Hernandez <marcelohdez.inq@gmail.com>"]
description = "Attempt quick, temporary code projects"
homepage = "https://github.com/marcelohdez/atmpt"
license = "GPL-3.0-only"
keywords = ["cli"]

version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
directories-next = "2.0.0"
clap = { version = "4.4.8", features = ["derive", "env"] }
chrono = "0.4.31"

[build-dependencies]
clap = { version = "4.4.8", features = ["derive", "env"] }
clap_complete = "4.4.4"

[dev-dependencies]
assert_cmd = "2.0.12"
