name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build -r --locked --verbose
      - name: Attach binary
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/atmpt
            target/release/atmpt.exe
