name: Rust build & tests

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          clippy: true
          rustfmt: true
      - name: Build locked
        run: cargo build --locked --verbose
      - name: Test locked
        run: cargo test --locked --verbose
